"""
Lexical Retrieval
Implements BM25-based lexical search and RAG pipeline.
"""
import re
import json
import requests
from rank_bm25 import BM25Okapi
from typing import List, Tuple

try:
    import ollama
except Exception:
    ollama = None

# Ollama model configuration
MODEL = "gemma3:4b"


def load_snippets(load_path="./output/snippets.json"):
    """
    Load chunked snippets generated by data ingestion.

    Args:
        load_path: Path to snippets JSON file

    Returns:
        List of snippet dictionaries
    """
    try:
        with open(load_path, "r", encoding="utf-8") as f:
            snippets = json.load(f)
        print(f"Successfully loaded {len(snippets)} snippets")
        return snippets
    except Exception as e:
        print(f"Failed to load snippets: {e}")
        return []


def preprocess_text(text: str) -> List[str]:
    """
    Clean and tokenize input text.

    Args:
        text: Input text to preprocess

    Returns:
        List of tokens
    """
    text = re.sub(r'[^\w\s]', ' ', text.lower())
    return text.split()


def lexical_search(query: str, snippets: List[dict], top_k: int = 3) -> List[Tuple[float, List[str], int]]:
    """
    BM25-based lexical search.

    Args:
        query: User query string
        snippets: List of snippet dictionaries with 'text' field
        top_k: Number of top results to return

    Returns:
        List of (score, overlap_keywords, snippet_index) tuples
    """
    snippet_texts = [s["text"] for s in snippets]
    tokenized_texts = [preprocess_text(t) for t in snippet_texts]
    tokenized_query = preprocess_text(query)

    bm25 = BM25Okapi(tokenized_texts)
    scores = bm25.get_scores(tokenized_query)

    top_indices = sorted(range(len(scores)),
                         key=lambda i: scores[i], reverse=True)[:top_k]

    results = []
    for idx in top_indices:
        overlap_keywords = list(set(tokenized_query) &
                                set(tokenized_texts[idx]))
        results.append((round(scores[idx], 4), overlap_keywords, idx))
    return results


def ollama_generate(prompt: str) -> str:
    """
    Ollama raw generation (matches template: raw=True).

    Args:
        prompt: Prompt text for generation

    Returns:
        Generated response text
    """
    if ollama is not None:
        response = ollama.generate(
            model=MODEL,
            prompt=prompt,
            stream=False,
            raw=True,
            options={
                "num_predict": 180,
                "temperature": 0.3
            }
        )
        return response["response"].strip()

    r = requests.post(
        "http://localhost:11434/api/generate",
        json={
            "model": MODEL,
            "prompt": prompt,
            "stream": False,
            "options": {
                "num_predict": 180,
                "temperature": 0.3,
            },
        },
        timeout=120,
    )
    r.raise_for_status()
    return str(r.json().get("response") or "").strip()


def answer_with_lexical_rag(query: str, snippets: List[dict], top_k: int = 3) -> str:
    """
    Full lexical RAG pipeline: retrieve → prompt → generate.

    Args:
        query: User query string
        snippets: List of snippet dictionaries
        top_k: Number of snippets to retrieve

    Returns:
        Generated answer with citations
    """
    search_results = lexical_search(query, snippets, top_k)
    if not search_results:
        return "No relevant information found."

    context_parts = []
    for i, (score, kw, idx) in enumerate(search_results):
        context_parts.append(f"[Snippet {i+1}] {snippets[idx]['text']}")
    context = "\n\n".join(context_parts)

    prompt = f"""Use only the context below to answer the question.
Cite snippet numbers like [1][2].

Context:
{context}

Question: {query}
Answer:"""

    return ollama_generate(prompt)


# Main execution
if __name__ == "__main__":
    # Load snippets
    snippets = load_snippets()

    if not snippets:
        print("Validation failed: please check snippets.json from data ingestion.")
        exit(1)

    # Test the full pipeline
    test_query = "What is academic advising?"

    print("\n=== Lexical Search Result ===")
    search_result = lexical_search(test_query, snippets)
    for score, overlap, idx in search_result:
        print(f"Score: {score} | Keywords: {overlap} | Index: {idx}")

    print("\n=== Lexical RAG Answer ===")
    answer = answer_with_lexical_rag(test_query, snippets)
    print(answer)

    # Final validation
    print("\n=== Validation ===")
    print("Validation passed!")
    print(f"Total snippets available: {len(snippets)}")
    print("lexical_search() and answer_with_lexical_rag() are ready.")
